### ISSUE TITLE
A new error occurred: "The "" scheme is not supported; supported schemes for mailer "smtp" are: "smtp", "smtps"."

### ISSUE THREAD

**Issue by ok200paul** [openfoodfoundation/vine#79]
There seems to be an issue with sending email from the staging system. Have a look at the environment files and ensure they align.

**Comment by RachL** [comment]
Thanks, I've bumped into this error yesterday, trying to change the password of a user I've created https://flareapp.io/share/B5ZJX325

**Comment by ok200paul** [comment]
Thanks Rachel! Seeing this on staging and on production. Keep these reports coming through.

Hey @mkllnk first off - not sure why this is happening. ChatGPT is telling me this error means we need to pop in a MAILER_DSN value into the env variables, something like the following:

MAILER_DSN=smtp://your_email@gmail.com:your_app_password@smtp.gmail.com:587?encryption=tls

We've previously not needed this and it worked. We have the following env var:

MAIL_FROM_ADDRESS="vine@openfoodnetwork.org.au"

.. could you grab me the password for this account so I can pop it into MAILER_DSN please?

**Comment by ok200paul** [comment]
Not here obviously ;)

**Comment by mkllnk** [comment]
We found the issue in Laravel:

* https://github.com/laravel/framework/issues/53721
